// On linux, you can compile and run it like so:
// g++ blur.cpp -g -std=c++11 -I /curr/jiajieli/Halide/include -I /curr/jiajieli/Halide/tools -L /curr/jiajieli/Halide/bin -lHalide `libpng-config --cflags --ldflags` -ljpeg -lpthread -ldl -o blur
// LD_LIBRARY_PATH=/curr/jiajieli/Halide/bin /curr/jiajieli/app_halide2heterocl/blur/codegen/blur
#include "Halide.h"
#include "fstream"
using namespace Halide;

int main(int argc, char **argv) {
    ImageParam input(type_of<uint8_t>(), 2);


    // input:rand_matrix generated by rand_generator.py
    // std::ifstream input_file ("/curr/jiajieli/app_halide2heterocl/blur/input_halide.txt");
    // if (input_file.is_open())
    // {     
    //     for (int y = 0; y < input.height(); y++){
    //         for (int x = 0; x < input.width(); x++){
    //             input_file >> input(x,y); 
    //         }
    //     }
    // }   
    

    Var x("x"), y("y");
    Func mean_local("mean_local");
    RDom box(0, 3, 0, 3);
    mean_local(x, y) += input(x + box.x, y + box.y) / (3 * 3); // median_blur.
    Func final("final");
    final(x, y) = mean_local(x, y);
    
    // can't use one function here: blur_x(x, y) = (blur_x(x, y) + blur_x(x, y+1) + blur_x(x, y+2)) / 3, if use recursive references, the index need to be the same. It seems to be a demand to protect scheduling
    // Error occured: All of a function's recursive references to itself must contain the same pure variables in the same places as on the left-hand-side.

    // unroll & reorder
    // blur_x.reorder(y, x);

    // blur_x.unroll_hcl(x, 4);
    // blur_y.unroll_hcl(x, 4);
    

    // blur_x.compute_root();
    // blur_y.compute_root();


    // CPU schedule - no schedule
    Var xi{"xi"}, yi{"yi"};
    // mean_local.compute_at(final, y)
    //          .vectorize(y, 8);
    // mean_local.tile(x, y, xi, yi, 4, 4)
    //         .parallel(xi)
    //         .vectorize(y, 4);
    

    mean_local.compile_to_static_library("median_blur_lib", {input}, "median_blur");



    return 0;
}