import numpy as np 
# output_heterocl = np.load("output_heterocl.npy")
output_halide_flat = np.loadtxt("output_halide.txt")
output_halide = np.transpose(output_halide_flat.reshape((3, 1278, 766)), (2, 1, 0)) # generated by new linear_blu.cpp: No boundary condition

# output_halide_split_flat = np.loadtxt("output_halide_split.txt")
# output_halide_split = np.transpose(output_halide_split_flat.reshape((3, 1278, 766)), (2, 1, 0)) # generated by new linear_blu.cpp: No boundary condition


output_heterocl_generate = np.load("output_heterocl_generate.npy")
# output_heterocl_reorder_generate = np.load("output_heterocl_reorder_generate.npy")
# output_heterocl_split_generate = np.load("output_heterocl_split_generate.npy")
output_heterocl_unroll_generate = np.load("output_heterocl_unroll_generate.npy")

def dif(a,b):
    return np.sum(np.abs(a - b)) / np.size(a)

print("halide and generate: no schedule: ", dif(output_halide, output_heterocl_generate))
# print("halide and generate: reorder: ", dif(output_halide, output_heterocl_reorder_generate)) 
# print("halide and generate: split (no remaining): ", dif(output_halide, output_heterocl_split_generate)) 
print("halide and generate: unroll: ", dif(output_halide, output_heterocl_unroll_generate)) # just like split + unroll(full)



# print("average element dif: (input between 0 to 100)")
# print(dif(output_halide, output_heterocl))

# print("output_heterocl_target shape: ", output_heterocl_target.shape)
# print("average element dif between hcl target and halide: ")
# print(dif(output_halide, output_heterocl_target))
# print("average element dif between hcl target and hcl original: ")
# print(dif(output_heterocl, output_heterocl_target))

# print("output_heterocl_target shape: ", output_heterocl_new_target.shape)
# print("average element dif between hcl new target and halide: ")
# print(dif(output_halide, output_heterocl_new_target))
# print("average element dif between hcl new target and hcl original: ")
# print(dif(output_heterocl, output_heterocl_new_target))

